version: '{build}'
os: Windows Server 2012

artifacts:
  - path: target\AtomUtils.jar
build_script:
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
